#+title: Woodworking projects
#+startup: overview
#+setupfile: wood.setup

* Pikler triangle
Date: 24 Dec 2024

https://live.staticflickr.com/65535/54227936817_92e9cabade_k.jpg

Desc: A climbing frame for Ayla made from Tasmanian Oak planks and Eucy dowel and finished with food grade parafin oil (mineral oil). Two areas for improvement: the forsner bit splintered the planks on the bottom side which would be solved by either using a scrap under or only drilling partially through so that dowels are recessed; and better glue cleanup since there are glue stains visible after finishing.

* High chair footrest
Date: 23 Nov 2024

https://live.staticflickr.com/65535/54227938772_0633a7a5dc_k.jpg

Desc: Footrest made for Kmart/Ikea high chair. Simple construction using an offcut of pine, cutting the side grooves with the router and finishing with parafin oil (mineral oil). It's held in place by 4 o-rings.

* Side table
Date: 26 Feb 2023

https://live.staticflickr.com/65535/52711573064_f9d01631e9_k.jpg

Desc: A side table for the corner of our room to hold charging cables. The timber was Okoume glulam panel finished with clear polyurethane. The draw was made from some scrap MDF with a plywood base and painted with Porter's Highland paint. Draw was tough to get in because of the little tolerance, but used some spacers to get the alignment correct.

* Balance board
Date: 6 Jan 2023

https://live.staticflickr.com/65535/52612943042_1f51c8d021_k.jpg

Desc: Design inspiration from the [[https://indoboardaus.com/][Indo Board]], this board was made from a 550mm x 18mm Round Okoume panel on special for $6. The edges were cut straight using a circular saw, then corners shaped with a jigsaw. The board edge was then routed with a quarter circle bit, sanded down and finished with clear polyurethane coating.

* Art print frame
Date: 6 Jan 2023

https://live.staticflickr.com/65535/52613710774_7df26ecaa6_k.jpg

Desc: This one was created in a couple of hours using some old trim scrap peices from the garage. They were sanded down, cut to size and then dowelled together (rather than a miter join). The fabric was then installed and tensioned using a staple gun.

* Workbench
Date: 3 Jan 2023

https://live.staticflickr.com/65535/52613451661_44a7722378_k.jpg

Desc: The worktop is created from an MDF panel with 20mm holes at 100CTS to suit bench dogs or clamps. It is also hollow under to allow easy clamping from most locations. The legs came from an old sleeper that was planed down; timber type unknown but has a reddish tint. The beams were planed down from some old 90x45 pine lengths. Legs and beams were joined using dowels and finished with clear polyurethane.

* Entryway bench
Date: 23 Dec 2022

https://live.staticflickr.com/65535/52612943117_4790209cec_k.jpg

Desc: Built to suit the Ikea entryway shelving the 18mm Red Oak panel was cut to size. The Ikea threaded inserts were installed in the panel, the front edge was routed using a quarter circle bit and finished with a coat of clear polyurethane.

* Plant ladder
Date: 18 Dec 2022

https://live.staticflickr.com/65535/52613451601_7051f58cde_k.jpg

Desc: This simple job was created from two square pine lengths and a dowel. The drill press was used to cut inserts for the dowel lengths and the ladder was assembled, no glue or fasteners.

* Builtin workbench
Date: 11 Dec 2022

https://live.staticflickr.com/65535/52612943002_f9d729c4ce_k.jpg

Desc: The garage builtin workbench was built using spoted gum panels (cheapest available panel), MDF board coated with BIN sealer for the supports, and standard pegboard panels. The bench panels are fixed to the studs using steel brackets. In hind sight I would've built a proper support rather than the MDF and focued on better quality levelling.

* Photo processing                                                 :noexport:
#+begin_src eshell
for f in *.jpg {convert $f -resize 25% $(file-name-sans-extension f)-small.jpg}
#+end_src

